import { Cpu, HardDrive, Languages, ListChecks } from 'lucide-react';
import { AppShell } from '@/components/layout/app-shell';
import { PageHeader, SectionCard } from '@/components/shared/cognix-primitives';
import { usageData } from '@/lib/researchData';

export default function UsagePage() {
  const translationRequests = 34;
  const driveExports = 12;
  return <AppShell><PageHeader title="Usage & Limits" description="Prototype usage counters reserved for backend metering." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="AI requests today" value={usageData.aiRequestsToday} limit={usageData.aiRequestsLimit} icon={Cpu} /><Metric label="Processing jobs" value={usageData.processingJobs} limit={100} icon={ListChecks} /><Metric label="Translation requests" value={translationRequests} limit={500} icon={Languages} /><Metric label="Drive exports" value={driveExports} limit={100} icon={HardDrive} /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><SectionCard title="Storage"><p className="text-3xl font-semibold font-mono-tight">{usageData.storageUsed}%</p><div className="mt-3 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${usageData.storageUsed}%`}} /></div><p className="mt-2 text-xs text-muted-foreground">{usageData.storageUsed} GB of {usageData.storageLimit} GB simulated.</p></SectionCard><SectionCard title="Metering notes"><ul className="space-y-2 text-sm text-muted-foreground"><li>• Translation requests count each provider call.</li><li>• Drive exports count successful packages, not retries.</li><li>• Failed jobs retain retry history for audit.</li></ul></SectionCard></div></AppShell>;
}
function Metric({label,value,limit,icon:Icon}:{label:string;value:number;limit:number;icon:typeof Cpu}){const pct=Math.min(100,value/limit*100);return <div className="surface-elevated rounded-xl p-5"><Icon className="h-5 w-5 text-primary"/><p className="mt-4 font-mono-tight text-2xl font-semibold">{value.toLocaleString()}</p><p className="text-xs text-muted-foreground">{label} / {limit.toLocaleString()}</p><div className="mt-3 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${pct}%`}} /></div></div>}
